name: Node.js Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout-repo:
    runs-on: 
      - self-hosted
      - label-1

    steps:
    - 
      name: Checkout repo
      uses: actions/checkout@v4
  
  docker-login:
    runs-on: 
      - self-hosted
      - label-1

    needs: checkout-repo

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  docker-build:
    runs-on: 
      - self-hosted
      - label-1

    needs: docker-login

    steps:
    - 
      name: Build Docker image
      run: |
        export DOCKER_BUILDKIT=1
        echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        docker build --secret id=env,src=.env -t ${{ secrets.DOCKER_USER }}/weather-app:latest .
  
  docker-run:
    runs-on: 
      - self-hosted
      - label-1

    needs: docker-build

    steps:      
    -
      name: Run docker container
      run: |
        docker run -d -p 3000:3000 -p 8080:8080 --name weather-app-new ${{ secrets.DOCKER_USER }}/weather-app:latest
  
  docker-push:
    runs-on: 
      - self-hosted
      - label-1

    needs: docker-run

    steps:
    -
      name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/weather-app:latest