name: Node.js Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout-repo:
    runs-on: 
      - self-hosted
      - label-1

    steps:
    - 
      name: Checkout repo
      uses: actions/checkout@v4
  
  docker-actions:
    runs-on: 
      - self-hosted
      - label-1

    needs: checkout-repo

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - 
      name: Build Docker image
      run: |
        export DOCKER_BUILDKIT=1
        docker build -t ${{ secrets.DOCKER_USER }}/weather-app-1:latest .
    
    -
      name: Run docker container
      run: |
        docker run -d -e API_KEY=${{ secrets.API_KEY }} -p 3000:3000 -p 8080:8080 --name weather-app-latest ${{ secrets.DOCKER_USER }}/weather-app-1:latest
  
    -
      name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/weather-app-1:latest