name: Node.js Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: 
      - self-hosted
      - label-1

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v4
  
  docker-login:
    runs-on: 
      - self-hosted
      - label-1

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  docker-image-build:
    runs-on: 
      - self-hosted
      - label-1

    steps:
    - 
      name: Build Docker image
      run: |
        export DOCKER_BUILDKIT=1
        echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        docker build --secret id=env,src=.env -t ${{ secrets.DOCKER_USER }}/weather-app:latest .

  docker-run:
    runs-on:
      - self-hosted
      - label-1

    steps:
    -
      name: Run docker container
      run: |
      d
      # -d --name weather-app-latest -p 8080:8080 ${{ secrets.DOCKER_USER }}/weather-app:latest
  

  docker-image-push:
    runs-on: 
      - self-hosted
      - label-1

    steps:
    -
      name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/weather-app:latest