name: Node.js Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: 
      - self-hosted
      - label-1

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v4

    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - 
      name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/weather-app:latest .

    -
      name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/weather-app:latest